### ISSUE TITLE
AWS_REGION env variable missing on jambonz-feature-server chart

### ISSUE THREAD

**Issue by juansalvatella** [jambonz/helm-charts#3]
The AWS_REGION env variable is missing on the jambonz-feature-server chart. By default it seems to pick up an american region which may work for some users but not for others.

**Comment by davehorton** [comment]
" it seems to pick up .." 
are you referring to when aws is used for speech services?  Or something else?

**Comment by juansalvatella** [comment]
Yes, I'm referring to when AWS is used for speech services.

This is the error that you get when the environment variable is not set.
```
0|jambonz-feature-server | Error [ConfigError]: Missing region in config
10|jambonz-feature-server |   at Request.VALIDATE_REGION (/home/admin/apps/jambonz-feature-server/node_modules/aws-sdk/lib/event_listeners.js:94:47)
10|jambonz-feature-server |   at Request.callListeners (/home/admin/apps/jambonz-feature-server/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
10|jambonz-feature-server |   at callNextListener (/home/admin/apps/jambonz-feature-server/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
10|jambonz-feature-server |   at /home/admin/apps/jambonz-feature-server/node_modules/aws-sdk/lib/event_listeners.js:86:9
10|jambonz-feature-server |   at finish (/home/admin/apps/jambonz-feature-server/node_modules/aws-sdk/lib/config.js:386:7)
10|jambonz-feature-server |   at /home/admin/apps/jambonz-feature-server/node_modules/aws-sdk/lib/config.js:404:9
10|jambonz-feature-server |   at Credentials.get (/home/admin/apps/jambonz-feature-server/node_modules/aws-sdk/lib/credentials.js:127:7)
10|jambonz-feature-server |   at getAsyncCredentials (/home/admin/apps/jambonz-feature-server/node_modules/aws-sdk/lib/config.js:398:24)
10|jambonz-feature-server |   at Config.getCredentials (/home/admin/apps/jambonz-feature-server/node_modules/aws-sdk/lib/config.js:418:9)
10|jambonz-feature-server |   at Request.VALIDATE_CREDENTIALS (/home/admin/apps/jambonz-feature-server/node_modules/aws-sdk/lib/event_listeners.js:81:26) {
10|jambonz-feature-server |  code: 'ConfigError',
10|jambonz-feature-server |  time: 2021-12-29T11:53:21.011Z
10|jambonz-feature-server | }
```

**Comment by davehorton** [comment]
yes, ok.  I think there is a different but related bug, which is that when provisioning speech services the portal/api should require you to provide a region.  it does not, so it currently looks for that variable.  I agree for now it should be in the helm chart until I make the fix to the portal/API.  Do you want to give me a PR for this?

**Comment by javibookline** [comment]
@davehorton I believe this issue can be closed as per https://github.com/jambonz/helm-charts/pull/4
